### ISSUE TITLE
All crash related commands and features crash when used on latest version of Oh My ZSH

### ISSUE THREAD

**Issue by YonatanAhituv** [molovo/crash#4]
Hello, I am using Oh My ZSH and whenever I throw an error or do a try command, ZSH immediately crashes. Not sure how to fix this. 

Crash Version: Latest (just cloned)
Terminal: iTerm2
Oh-My-ZSH Version: Latest

**Comment by molovo** [comment]
Are you using `crash` within a script, or just calling `throw` on the command line? If it's on the command line, then that's expected behaviour (`throw` kills the current process so that `try`/`catch` can handle it).

If it's in a script, could you please post a simplified test case which produces the error so that I can look into it? Thanks

**Comment by YonatanAhituv** [comment]
When using the example in the README or simply typing the command: "crash". ZSH immediately crashes:
[https://asciinema.org/a/7PWY97HinTtBErViBZv1fpYp6](https://asciinema.org/a/7PWY97HinTtBErViBZv1fpYp6)

**Comment by molovo** [comment]
Yes, `crash` isn't designed to be used on the command line - it has no use there at all. The only command within the `crash` script is `crash register`, hence why you receive the error message.

If you use crash within a ZSH program, once you've run `autoload -Uz crash && crash register` it makes the functions `throw`, `try` and `catch` available to you to use in your script, like in [this example](https://github.com/molovo/crash#trycatch).

**Comment by YonatanAhituv** [comment]
This does not just happen when running the crash command, it also happens with throw, but rsther than the program with the exception closing, the entirety of ZSH crashes.
